DROP DATABASE PORTFOLIO_DATABASE;

CREATE DATABASE PORTFOLIO_DATABASE;

USE PORTFOLIO_DATABASE;

CREATE TABLE PORTFOLIO_LOGIN
(
  username VARCHAR(50) PRIMARY KEY,
  password VARCHAR(50)
);

INSERT INTO PORTFOLIO_LOGIN VALUES ('admin','admin');

CREATE TABLE PROJECTS_PORTFOLIO
(
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(50) NOT NULL,
  description VARCHAR(150),
  service VARCHAR(50),
  client VARCHAR(50),
  date DATE,
  image VARCHAR(50)
);

INSERT INTO PROJECTS_PORTFOLIO (TITLE, DESCRIPTION, SERVICE, CLIENT, DATE, IMAGE) VALUES ('Project One','Web Development','Develops Website','Client One','2015-01-01','cake.png');
INSERT INTO PROJECTS_PORTFOLIO (TITLE, DESCRIPTION, SERVICE, CLIENT, DATE, IMAGE) VALUES ('Project Two','Web Design','Designs Website','Client Two','2016-02-01','circus.png');
